//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Login_System.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;
    using System.ComponentModel.DataAnnotations;

    public partial class User
    {
        public int Id { get; set; }

        //Firstname Field
        [DisplayName("First name")]
        [Required(ErrorMessage = "Firstname is required")]
        public string Firstname { get; set; }

        //Lastname Field
        [DisplayName("Last name")]
        [Required(ErrorMessage = "lastname is required")]
        public string Lastname { get; set; }

        //Email Field
        [DisplayName("Email")]
        [Required(ErrorMessage = "Email is required")]
        //[RegularExpression("/^.+@.+$/", ErrorMessage = "Email is not valid")]
        public string Email { get; set; }
        //Gender Field
        [Required(ErrorMessage = "Gender is required")]
        public string Gender { get; set; }

        //Password Field
        [DisplayName("Password")]
        [Required(ErrorMessage = "Password is required")]
        [DataType(DataType.Password)]
        [MinLength(5, ErrorMessage = "Password should be atleat 5 characters")]
        public string Password { get; set; }

        //Confirm Password Field
        [DisplayName("Confirm Passoword")]
        [Required(ErrorMessage = "Confirmation is required")]
        [DataType(DataType.Password)]
        [Compare("Password", ErrorMessage = "Passwords do not match!")]
        public string ConfirmPassword { get; set; }
    }
}
